### ISSUE TITLE
Sobre las issues que podemos hacer

### ISSUE THREAD

**Issue by pedroriosg** [IIC2113/Syllabus#1]
Hola! Quería saber que tan específicos podríamos ser al realizar preguntas sobre la entrega. Principalmente porque somos nosotros quienes tenemos que decidir que diagrama UML usar para cada vista, pero hacer una pregunta sobre un diagrama en específico podría ser dar información.

Quedo atento!

**Comment by Dnpoblete** [comment]
Hola @pedroriosg! Puedes hacer preguntas sobre diagramas especificos, sin ningún problema 😄. Eso si, lo que no puedes hacer de ninguna forma es adjuntar tu solución o parte de esta en la pregunta 🙅‍♀️. En caso de que tengas una duda muy especifica sobre tu solución, te recomiendo preguntarla de forma análoga refiriéndote a otra situación o dando algún ejemplo similar, de tal forma que podamos resolver tu duda.

Mucho éxito con la entrega y quedamos atentos a tus dudas ✨
