### ISSUE TITLE
[Todos] APIs y datos externos

### ISSUE THREAD

**Issue by benjavicente** [IIC2113/Syllabus#11]
¿Podemos usar APIs o datos externos de utilidad (ej: datos de relleno, imágenes, json, faker)?

**Comment by Dnpoblete** [comment]
Hola @benjavicente, si esta permitido que utilicen APIs o datos externos de utilidad. De hecho es mejor mientras más creativos sean. Eso si recuerden documentar.

¡Mucho éxito con la entrega! :sparkles:
