### ISSUE TITLE
[Control 2 - P1] Identificar más de 3 problemas

### ISSUE THREAD

**Issue by fagiannoni** [IIC2113/Syllabus#15]
¡Hola!

Quería saber si se puede, y si es que sirve hacerlo en cuanto a posible puntaje otorgado, identificar y explicar más de tres problemas en el código.

Gracias desde ya, saludos 👋

**Comment by Dnpoblete** [comment]
Hola @fagiannoni! Sabemos que hay más de 3 problemas en el código, pero les pedimos únicamente tres, ya que con eso es suficiente para evaluar lo que busca la pregunta. Lamentablemente, dado que son muchas respuestas a revisar solo revisaremos las primeras tres que escriban, por lo que te recomiendo confiar en lo que sabes, seleccionar los problemas que te parezcan más fáciles de arreglar y explicar con detalle como los solucionarías.

Mucho éxito! ✨

**Comment by fagiannoni** [comment]
Ok, ¡muchas gracias!
