### ISSUE TITLE
Parámetros en módulos no entregados 

### ISSUE THREAD

**Issue by benjavicente** [IIC2113/Syllabus#16]
Hola!

¿Asumimos que los módulos no incluidos (`shipping_service`, `payments_service`) no se les puede hacer refractoring, como si fuera una API externa (que no le podemos modificar los parámetros)?

Gracias de antemano!

**Comment by aaossa** [comment]
Hola @benjavicente , **sí pueden proponer cambios en esos módulos no incluidos, pero tienen que ser efecto de un refactoring en los módulos que sí se incluyeron**. Por ejemplo, puedes proponer agregar un método en una de esas clases o modificar sus argumentos, incluso puedes proponer crear nuevos módulos, pero siempre como efecto de un refactoring en el programa "visible", en los archivos que sí les dimos. 

¡Éxito en el control 🙌 !
