### ISSUE TITLE
[Control 2] Pregunta 2

### ISSUE THREAD

**Issue by mafernandez9** [IIC2113/Syllabus#17]
Hola! Me surgió una duda respecto a qué se refieren con módulos. Los módulos serían métodos en sí, o se refieren a archivos completos? Muchas gracias de antemano!

**Comment by Dnpoblete** [comment]
Hola @mafernandez9 ! Con módulo nos referimos a una pieza de software que hace lo mencionado en el enunciado. No es tan relevante si es método o archivo, sino que lo importante es la funcionalidad mencionada.

Mucho éxito y quedo atenta en caso de que aún tengas dudas! ✨

**Comment by mafernandez9** [comment]
Super! muchas gracias!!
