### ISSUE TITLE
Profundidad esperada en la pregunta 3

### ISSUE THREAD

**Issue by benjavicente** [IIC2113/Syllabus#18]
En la pregunta 3 del control se recomienda indicar _casos bordes, ejemplos de inputs y output esperados, etc._ ¿Tenemos que dejar explícitamente como serán los tests, o podemos proponer una estrategia como se tiene que hacer en la pregunta 1 (no dejando explicito input/output esperado)?

Gracias de antemano!

**Comment by Dnpoblete** [comment]
Hola @benjavicente ! Para esta pregunta no es necesario ser tan detallado en decir input/output específicos, pero tampoco puede ser una respuesta genérica. Lo ideal sería decir cuantos tests harían, explicitando los casos y decir que valores sirven para esos casos. Ejemplo: Haría 5 tests, el primero sería X  para probar X cosa, el segundo sería … bla bla.

Mucho éxito y quedo atenta en caso de que aún tengas dudas! ✨
