### ISSUE TITLE
Diagrama de clases - métodos

### ISSUE THREAD

**Issue by pedroriosg** [IIC2113/Syllabus#2]
Hola! Si hay una entidad que puede realizar operaciones CRUD sobre varias, tenemos que indicar en sus métodos cada operacion por separado? O podemos poner solo uno que haga referencia a las 4 operaciones.

Saludos!

**Comment by pedroriosg** [comment]
Sí, en el enunciado hay una entidad que se relaciona con todas, que es capaz de crear, eliminar, etc a otras. Entonces mi pregunta es si en los métodos de esa entidad tenemos que especificar si crear, eliminar, etc a cada entidad con la que se relaciona. Ahí se entiende más?

**Comment by Dnpoblete** [comment]
Entiendo lo que me comentas, pero no veo eso en ninguno de los tres proyectos, podrías especificarme el proyecto al que te refieres?

**Comment by pedroriosg** [comment]
En ecommerce!
