### ISSUE TITLE
Notas Control 2

### ISSUE THREAD

**Issue by josemquinta15** [IIC2113/Syllabus#22]
Hola!,

Quería saber como va la corrección del control 2 y si hay alguna fecha aprox para cuando estén listas. Para poder planificar de mejor manera el resto del semestre.

Saludos

**Comment by Dnpoblete** [comment]
Hola @josemquinta15! Estarán a más tardar dentro de los 15 días hábiles que tenemos para revisar, lo cual si no me equivoco debería ser este viernes.
