### ISSUE TITLE
Comparación de diagramas entre un mismo equipo

### ISSUE THREAD

**Issue by CristianD16** [IIC2113/Syllabus#4]
Hola!
Es posible entregar los mismos diagramas entre miembros de un mismo equipo??

**Comment by Dnpoblete** [comment]
Hola @CristianD16 ! Esta entrega es inidividual 👀, por lo que se espera que cada estudiante desarrolle y entregue su solución por separado. Si bien esta permitido que comenten sus ideas con sus grupos si es que ya los tienen, el entregar respuestas muy similiares o iguales con otros estudiantes del curso podría ser considerado copia.

Éxito con la entrega y quedo atenta en caso de que tengas más dudas! ✨

**Comment by Dnpoblete** [comment]
Hola @CristianD16, perdón por la respuesta anterior, hubo una descordinación por parte del equipo docente. Tal como dices, integrantes de un mismo grupo pueden entregar los mismos diagramas, pero recuerda que son 3 integrantes por grupo. De todas maneras, tal como les mencionó el profesor en clase, esta evaluación está pensada para que una persona pueda hacer los 5 diagramas y así conocer los posibles diagramas para cada vista del Modelo 4+1. Adicionalmente, se espera que todos los integrantes manejen los contenidos evaluados en esta entrega.

Mucho éxito con la entrega y quedo atenta en caso de que aún tengas dudas ✨
