### ISSUE TITLE
Dudas generales del proyecto

### ISSUE THREAD

**Issue by benjavicente** [IIC2113/Syllabus#5]
> Todavía no se ha hecho una issue con dudas generales del proyecto, así que aquí voy 😅

- #7
- #8
- #9
- #10 (movido a #6)
- #11
- #12

Gracias de antemano!

Edit: convertido a lista de issues

**Comment by domingo2000** [comment]
Me sumo a las dudas con lo siguiente:
- [Eccomerce] ¿Se pueden usar librerías de componentes de terceros como MaterialUI o ReactBootstrap?
- [Eccomerce]: Podrían dar un listado de librerías permitidas/prohibidas o hacer una issue especial de eso. se me vienen a la mente las siguientes:
1. Componentes: Material UI,  React Bootstrap
2. Css: sass, tailwind
3. Forms: Formik, Yup
4. Routing: ReactRouter
5. Data Fetching: Axios, Apolo

**Comment by Dnpoblete** [comment]
Hola @benjavicente y @domingo2000, entiendo que tengan varias dudas con respecto a la entrega, pero les voy a pedir que por favor realicen una issue por pregunta, indicando el proyecto y tema de la pregunta, de tal forma de que sea más fácil de responder para les ayudantes y más fácil de buscar para otres estudiantes con las mismas dudas.

Gracias y quedo atenta a cuando creen las issues! :sparkles:
