### ISSUE TITLE
[React] Dependencias Permitidas Eccomerce Frontend (React)

### ISSUE THREAD

**Issue by domingo2000** [IIC2113/Syllabus#6]
Hola, me surge la duda de cual es la flexibilidad para usar diferentes dependencias en el proyecto, específicamente en la parte del Frontend de React en el proyecto de eccomerce:

1. Componentes: Material UI,  React Bootstrap
2. Css: sass, tailwind
3. Forms: Formik, Yup
4. Routing: ReactRouter
5. Data Fetching: Axios, Apolo

**Comment by nmassardot** [comment]
Hola! De las que nombraste, las únicas que **NO** están permitidas son las del punto 1. Es decir, no puedes usar Material UI, React Bootstrap ni nada semejante

**Comment by benjavicente** [comment]
Duda: donde entran los componentes de **lógica**? Por ejemplo [headlessUI](https://headlessui.dev/). Es como la misma idea que formkit, entregando herramientas para desarrollar interfaces, pero sin entregar estilo y componentes completamente prehechos.

**Comment by nicolascamhi** [comment]
Bulma se puede usar?

**Comment by kelseyfranken** [comment]
Hola! se puede usar [Bulma](https://bulma.io/)?

**Comment by francisca0308** [comment]
Hola!
Se podría usar una librería que se llama [usePersistedState?](https://github.com/giovannibenussi/use-persisted-state-hook)
