### ISSUE TITLE
[Todos] ¿La API tiene que ser RESTful?

### ISSUE THREAD

**Issue by benjavicente** [IIC2113/Syllabus#9]
¿La API tiene que ser RESTful (y no por ejemplo con GraphQL)?

**Comment by aaossa** [comment]
¡Hola! Aquí la respuesta es más o menos la misma que en #7 : **deben confirmar con quien sea ayudante asignado a su equipo**, ya que depende tanto del proyecto como de la justificación para utilizar X tecnología
